// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240322190919_entitiesConfigs")]
    partial class entitiesConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4ab97c50-052f-44af-8516-3a27e4ec3d72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40f438ba-5f3e-49ed-a4a4-ea766deba087",
                            Email = "admin1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDMu6MTeAOd+z+kePslZ41UKzYagmKzDl6mCA8sxv5Cc9bCb7gKQ7t2HwUPc0h1EMQ==",
                            PersonId = 1,
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "75797fe9-0148-4850-a731-dd88753ce293",
                            TwoFactorEnabled = false,
                            UserName = "admin1@example.com"
                        },
                        new
                        {
                            Id = "faa2cd95-a59c-4127-8f54-916deb38b612",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d144a35b-71d8-4837-b4da-228e0f7a426e",
                            Email = "admin2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECW8okXGDOcn5ui5psBozeDLx406AyyxlB50JijlYJxHTR9ImRm+iEJ07BR1bnAbnA==",
                            PersonId = 2,
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "aaa628e8-bcaa-43aa-9faf-152d7bc70d90",
                            TwoFactorEnabled = false,
                            UserName = "admin2@example.com"
                        },
                        new
                        {
                            Id = "ea4cbaeb-0869-493c-b80c-372a32b05539",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1cede3b-495e-4ba4-9d7d-fffd1723c44f",
                            Email = "client1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT1@EXAMPLE.COM",
                            NormalizedUserName = "client1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEN+g1pIKErOnJhdlECPbZTVGbgYxvmvO4d04bckUSk80UGymFZO1zFgBV0J107ay/Q==",
                            PersonId = 3,
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "14fb52c7-3a82-4767-8756-ead31702726d",
                            TwoFactorEnabled = false,
                            UserName = "client1@example.com"
                        },
                        new
                        {
                            Id = "55f7cc01-0e49-4cb0-bff8-aced0c399819",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2aa7b07e-7629-49ed-a5bd-4bfdfbfb3455",
                            Email = "client2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT12@EXAMPLE.COM",
                            NormalizedUserName = "CLIENT12@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEPnafCDLG+ptQQCJH54FznLdqv1OFs1VKzEPstEFgSTMO9uTlFc3hc5T0BEp6XYsw==",
                            PersonId = 4,
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "a84f49bc-7062-42c1-a001-89cdfd73af77",
                            TwoFactorEnabled = false,
                            UserName = "client2@example.com"
                        },
                        new
                        {
                            Id = "064b6a0b-8c25-4710-8fc3-95e2d59be04e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f411e0ea-e26f-4bf5-92cf-ecb867406cd4",
                            Email = "client3@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT3@EXAMPLE.COM",
                            NormalizedUserName = "CLIENT3@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE4czwQLVWIvDq40mACa9zGflnFBXFnc+vvKTbBovUjKowbRD7PKIDyaP9QSM2Ef6A==",
                            PersonId = 5,
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisteredDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "3f5fac69-b398-463e-9c00-aa3a2ba73008",
                            TwoFactorEnabled = false,
                            UserName = "client3@example.com"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentDetail", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentExerciseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentDetailAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRepetitions")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RestAfterExerciseInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RestBetweenSetsInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("SuccessfulyPerformed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDetailAppointmentId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("AppointmentExerciseDetails");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentServiceTypeDurationCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeDurationCostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ServiceTypeDurationCostId");

                    b.ToTable("AppointmentServiceTypeDurationCosts");
                });

            modelBuilder.Entity("DataAccess.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("HTMLContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordsString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("DataAccess.Entities.BookedAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentBookedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AppointmentServiceTypeDurationCostId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("OneDayReminderSent")
                        .HasColumnType("bit");

                    b.Property<bool>("SevenDaysReminderSent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentServiceTypeDurationCostId");

                    b.HasIndex("ClientId");

                    b.ToTable("BookedAppointments");
                });

            modelBuilder.Entity("DataAccess.Entities.Client", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            PersonId = 3
                        },
                        new
                        {
                            PersonId = 4
                        },
                        new
                        {
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.ClientNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientNotes");
                });

            modelBuilder.Entity("DataAccess.Entities.DurationCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DurationCosts");
                });

            modelBuilder.Entity("DataAccess.Entities.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pull Up"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Push Up"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sit Up"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Jumping Jacks"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Squat Jumps"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Box Jumps"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Wall Balls"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kettlebell Swings"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Thrusters"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Power Cleans"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Snatches"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Overhead Squat"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Back Squat"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Sumo Deadlift High Pull"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Turkish Get Up"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Handstand Push Up"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Muscle Up"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Toes to Bar"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Double Unders"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Skipping Rope"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            LastName = "One",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Admin",
                            LastName = "Two",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Client",
                            LastName = "One",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Client",
                            LastName = "Two",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Client",
                            LastName = "Three",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("DataAccess.Entities.ServiceTypeDurationCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationCostId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DurationCostId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceTypeDurationCosts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8036F52A-701F-4AA4-8639-D9C8123FD8C6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "C7D20194-9C7E-40DB-9C63-F71D20116529",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4ab97c50-052f-44af-8516-3a27e4ec3d72",
                            RoleId = "8036F52A-701F-4AA4-8639-D9C8123FD8C6"
                        },
                        new
                        {
                            UserId = "faa2cd95-a59c-4127-8f54-916deb38b612",
                            RoleId = "8036F52A-701F-4AA4-8639-D9C8123FD8C6"
                        },
                        new
                        {
                            UserId = "ea4cbaeb-0869-493c-b80c-372a32b05539",
                            RoleId = "C7D20194-9C7E-40DB-9C63-F71D20116529"
                        },
                        new
                        {
                            UserId = "55f7cc01-0e49-4cb0-bff8-aced0c399819",
                            RoleId = "C7D20194-9C7E-40DB-9C63-F71D20116529"
                        },
                        new
                        {
                            UserId = "064b6a0b-8c25-4710-8fc3-95e2d59be04e",
                            RoleId = "C7D20194-9C7E-40DB-9C63-F71D20116529"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccess.Entities.ApplicationUser", b =>
                {
                    b.HasOne("DataAccess.Entities.Person", "Person")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("DataAccess.Entities.ApplicationUser", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentDetail", b =>
                {
                    b.HasOne("DataAccess.Entities.Appointment", "Appointment")
                        .WithOne("AppointmentDetail")
                        .HasForeignKey("DataAccess.Entities.AppointmentDetail", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentExerciseDetail", b =>
                {
                    b.HasOne("DataAccess.Entities.AppointmentDetail", null)
                        .WithMany("AppointmentExerciseDetails")
                        .HasForeignKey("AppointmentDetailAppointmentId");

                    b.HasOne("DataAccess.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentServiceTypeDurationCost", b =>
                {
                    b.HasOne("DataAccess.Entities.Appointment", "Appointment")
                        .WithMany("AppointmentServiceTypeDurationCosts")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.ServiceTypeDurationCost", "ServiceTypeDurationCost")
                        .WithMany("AppointmentServiceTypeDurationCosts")
                        .HasForeignKey("ServiceTypeDurationCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ServiceTypeDurationCost");
                });

            modelBuilder.Entity("DataAccess.Entities.BookedAppointment", b =>
                {
                    b.HasOne("DataAccess.Entities.AppointmentServiceTypeDurationCost", "AppointmentServiceTypeDurationCost")
                        .WithMany("BookedAppointments")
                        .HasForeignKey("AppointmentServiceTypeDurationCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Client", "Client")
                        .WithMany("BookedAppointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentServiceTypeDurationCost");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccess.Entities.Client", b =>
                {
                    b.HasOne("DataAccess.Entities.Person", "Person")
                        .WithOne("Client")
                        .HasForeignKey("DataAccess.Entities.Client", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DataAccess.Entities.ClientNote", b =>
                {
                    b.HasOne("DataAccess.Entities.Client", "Client")
                        .WithMany("ClientNotes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccess.Entities.ServiceTypeDurationCost", b =>
                {
                    b.HasOne("DataAccess.Entities.DurationCost", "DurationCost")
                        .WithMany("ServiceTypeDurationCosts")
                        .HasForeignKey("DurationCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceTypeDurationCosts")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DurationCost");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Appointment", b =>
                {
                    b.Navigation("AppointmentDetail");

                    b.Navigation("AppointmentServiceTypeDurationCosts");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentDetail", b =>
                {
                    b.Navigation("AppointmentExerciseDetails");
                });

            modelBuilder.Entity("DataAccess.Entities.AppointmentServiceTypeDurationCost", b =>
                {
                    b.Navigation("BookedAppointments");
                });

            modelBuilder.Entity("DataAccess.Entities.Client", b =>
                {
                    b.Navigation("BookedAppointments");

                    b.Navigation("ClientNotes");
                });

            modelBuilder.Entity("DataAccess.Entities.DurationCost", b =>
                {
                    b.Navigation("ServiceTypeDurationCosts");
                });

            modelBuilder.Entity("DataAccess.Entities.Person", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccess.Entities.ServiceType", b =>
                {
                    b.Navigation("ServiceTypeDurationCosts");
                });

            modelBuilder.Entity("DataAccess.Entities.ServiceTypeDurationCost", b =>
                {
                    b.Navigation("AppointmentServiceTypeDurationCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
